apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: my-php-app
    name: deployment-my-php-app
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 1
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: my-php-app
    template:
        metadata:
            labels:
                app: my-php-app
        spec:
            containers:
                -   
                    name: nginx
                    image: rafikarhaiem/nginx-app:v1
                    imagePullPolicy: Always
                    ports:
                        - 
                            containerPort: 80
                    volumeMounts:
                        - 
                            name: volume-nginx
                            mountPath: /etc/nginx/conf.d/default.conf
                            subPath: default-conf-file
                -
                    name: php
                    image: rafikarhaiem/php-app:v1
                    imagePullPolicy: Always
                    envFrom:
                        - 
                            configMapRef:
                                name: configmap-php-env
            volumes:
                - 
                    name: volume-nginx
                    configMap:
                        name: configmap-nginx
                
