apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: base64:nqFxOgBxRPOo9PQfMeYw16nxl5Jl+HpHHfFwBWvHPs0=
  APP_NAME: Laravel
  APP_URL: http://localhost
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: laravel
  DB_HOST: 127.0.0.1
  DB_PASSWORD: user
  DB_PORT: "3306"
  DB_USERNAME: user
  FILESYSTEM_DISK: local
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: '"hello@example.com"'
  MAIL_FROM_NAME: '"${APP_NAME}"'
  MAIL_HOST: mailhog
  MAIL_MAILER: smtp
  MAIL_PASSWORD: "null"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MEMCACHED_HOST: 127.0.0.1
  MIX_PUSHER_APP_CLUSTER: '"${PUSHER_APP_CLUSTER}"'
  MIX_PUSHER_APP_KEY: '"${PUSHER_APP_KEY}"'
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_CONNECTION: sync
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-php-env
